services:
  mlflow-service:
    image: ghcr.io/mlflow/mlflow:v2.15.1
    environment:
      MLFLOW_S3_ENDPOINT_URL: https://storage.yandexcloud.net
      # Здесь они нужны для доступа из UI
      AWS_ENDPOINT_URL: https://storage.yandexcloud.net
      AWS_ACCESS_KEY_ID: Yy
      AWS_SECRET_ACCESS_KEY: Yy
      AWS_DEFAULT_REGION: ru-central1
    command:
      - bash
      - -c
      - |
        pip install boto3 --quiet
        mlflow server --host 0.0.0.0 \
            --default-artifact-root s3://test-mlops2 --serve-artifacts
    expose:
      - "5000"
    ports:
      - "5050:5000"
    volumes:
      - mlflow-data:/mlflow

volumes:
  mlflow-data:
